package stats;

public enum Habilidad {


    CACOFONIA,LLOVIZNA,IMPULSO,ARMADURA_BATALLA,ROBUSTEZ,HUMEDAD,FLEXIBILIDAD,VELO_ARENA,
    ELECTRICIDAD_ESTATICA,ABSORBE_ELECTRICIDAD,ABSORBE_AGUA,DESPISTE,ACLIMATACION,OJO_COMPUESTO,
    INSOMNIO,CAMBIO_COLOR,INMUNIDAD,ABSORBE_FUEGO,POLVO_ESCUDO,RITMO_PROPIO,VENTOSAS,INTIMIDACION,
    SOMBRA_TRAMPA,PIEL_TOSCA,SUPERGUARDA,LEVITACION,EFECTO_ESPORA,SINCRONIA,CUERPO_PURO,CURA_NATURAL,
    PARARRAYOS, DICHA,NADO_RAPIDO,CLOROFILA,ILUMINACION,RASTRO,POTENCIA,PUNTO_TOXICO,FOCO_INTERNO,
    ESCUDO_MAGMA, VELO_AGUA,IMAN,INSONORIZAR,CURA_LLUVIA,CHORRO_ARENA,PRESION,SEBO,MADRUGAR,
    CUERPO_LLAMA,FUGA, VISTA_LINCE,CORTE_FUERTE,RECOGIDA,AUSENTE,ENTUSIASMO,GRAN_ENCANTO,MAS,MENOS,
    PREDICCION,VISCOSIDAD, MUDAR,AGALLAS,ESCAMA_ESPECIAL,LODO_LIQUIDO,ESPESURA,MAR_LLAMAS,TORRENTE,
    ENJAMBRE,CABEZA_ROCA, SEQUIA,TRAMPA_ARENA,ESPIRITU_VITAL,HUMO_BLANCO,ENERGIA_PURA,CAPARAZON,
    BUCLE_AIRE,TUMBOS,ELECTROMOTOR,RIVALIDAD,IMPASIBLE,MANTO_NIVEO,GULA,IRASCIBLE,LIVIANO,IGNIFUGO,
    SIMPLE,PIEL_SECA,DESCARGA,PUNO_FERREO,ANTIDOTO,ADAPTABLE,ENCADENADO,HIDRATACION,PODER_SOLAR,
    PIES_RAPIDOS,NORMALIDAD,FRANCOTIRADOR,MURO_MAGICO,INDEFENSO,REZAGADO, EXPERTO, DEFENSA_HOJA,
    ZOQUETE,ROMPEMOLDES,AFORTUNADO,DETONACION,ANTICIPACION,ALERTA,IGNORANTE,CROMOLENTE,FILTRO,
    INICIO_LENTO,INTREPIDO,COLECTOR,GELIDO,ROCA_SOLIDA,NEVADA,RECOGEMIEL,CACHEO,AUDAZ,MULTITIPO,
    DON_FLORAL,MAL_SUENO,HURTO,POTENCIA_BRUTA,RESPONDON,NERVIOSISMO,COMPETITIVO, FLAQUEZA,
    CUERPO_MALDITO,ALMA_CURA,COMPIESCOLTA,ARMADURA_FRAGIL,METAL_PESADO,METAL_LIVIANO,MULTIESCAMAS,
    IMPETU_TOXICO,IMPETU_ARDIENTE,COSECHA,TELEPATIA,VELETA,FUNDA,TOQUE_TOXICO,REGENERACION,
    SACAPECHO,IMPETU_ARENA,PIEL_MILAGRO,CALCULO_FINAL,ILUSION,IMPOSTOR,ALLANAMIENTO,MOMIA,AUTOESTIMA,
    JUSTICIERO,COBARDIA,ESPEJO_MAGICO,HERBIVORO,BROMISTA,PODER_ARENA, PUNTA_ACERO,MODO_DARUMA,
    TINOVICTORIA,TURBOLLAMA,TERRAVOLTAJE,VELO_AROMA,VELO_FLOR,CARRILLO,MUTATIPO,PELAJE_RECIO,
    PRESTIDIGITADOR,ANTIBALAS,TENACIDAD,MANDIBULA_FUERTE,PIEL_HELADA,VELO_DULCE,CAMBIO_TACTICO,
    ALAS_VENDAVAL,MEGADISPARADOR,MANTO_FRONDOSO,SIMBIOSIS, GARRA_DURA,PIEL_FEERICA,BABA,PIEL_CELESTE,
    AMOR_FILIAL,AURA_OSCURA,AURA_FEERICA,ROMPEAURA, MAR_DEL_ALBOR, TIERRA_DEL_OCASO,RAFAGA_DELTA,
    FIRMEZA,HUIDA,RETIRADA,HIDRORREFUERZO,ENSANAMIENTO, ESCUDO_LIMITADO,VIGILANTE,POMPA,ACERO_TEMPLADO,
    COLERA,QUITANIEVES,REMOTO,VOZ_FLUIDA,PRIMER_AUXILIO, PIEL_ELECTRICA,COLA_SURF,BANCO,DISFRAZ,
    FUERTE_AFECTO,AGRUPAMIENTO, CORROSION,LETARGO_PERENNE, REGIA_PRESENCIA,REVES,PAREJA_DE_BAILE,BATERIA,
    PELUCHE,CUERPO_VIVIDO,CORANIMA,RIZOS_REBELDES,RECEPTOR,REACCION_QUIMICA,ULTRAIMPULSO,SISTEMA_ALFA,
    ELECTROGENESIS,PSICOGENESIS,NEBULOGENESIS,HERBOGENESIS,GUARDIA_METALICA,GUARDIA_ESPECTRO,
    ARMADURA_PRISMA,FUERZA_CEREBRAL,ESPADA_INDOMITA,ESCUDO_RECIO,LIBERO,RECOGEBOLAS,PELUSA,HELICE_CAUDAL,
    CORAZA_REFLEJO,TRAGAMISIL,ACERRIMO,COMBUSTIBLE,PUNK_ROCK,EXPULSARENA,ESCAMA_DE_HIELO,
    MADURACION,CARA_DE_HIELO,FUENTE_ENERGIA,MIMETISMO,ANTIBARRERA,ALMA_ACERADA,CUERPO_MORTAL,ALMA_ERRANTE,
    MONOTEMA,GAS_REACTIVO,VELO_PASTEL,MUTAPETITO,MANO_RAPIDA,PUNO_INVISIBLE,MEDICINA_EXTRANA,TRANSISTOR,
    MANDIBULA_DRAGON,RELINCHO_BLANCO,RELINCHO_NEGRO,UNIDAD_ECUESTRE;

    Habilidad() {
    }

    @Override
    public String toString() {
        return "Stats.Habilidad{}";
    }
}
