package moves;

public enum AllMoves {


    ABSORBER,ACIDO,ACIDO_MALICO,ACOSO,AEROCHORRO,AGUA_LODOSA,AGUJERO_NEGRO_ANIQUILADOR,AIRE_AFILADO,ALA_AURAL,
    ALA_MORTIFERA,ALARIDO,ALBOROTO,ALTO_VOLTAJE,AMPLIFICADOR,ANILLO_IGNEO,APLASTAMIENTO_GIGALITICO,
    ARENAS_ARDIENTES,ARIA_BURBUJA,ARRUMACO_SIDERAL,AS_OCULTO,ASCUAS,BARRENA_TELURICA,BESO_DRENAJE,BOFETON_LODO,
    BOLA_DE_POLEN,BOLA_NEBLINA,BOLA_SOMBRA,BOLA_VOLTIO,BOMBA_ACIDA,BOMBA_FANGO,BOMBA_IGNEA,BOMBA_LODO,BOMBA_SONICA,
    BRILLO_MAGICO,BRUMA_EXPLOSIVA,BURBUJA,CABEZA_SORPRESA,CALCINACION,CANON,CANTO_ARCAICO,CAÑON_DINAMAX,CAÑON_FLORAL,
    CARGA_PARABOLA,CARGA_TOXICA,CARRERA_ARROLLADORA,CAUTIVAPOR,CHACHARA,CHISPAZO,CHORRO_DE_VAPOR,CICLON,
    CICLON_DE_HOJAS,CICLON_PRIMAVERA,CLOROFILASER,COLERA_DEL_GUARDIAN,COMESUEÑOS,COMETA_DRACO,CONFUSION,
    CONJURO_FUNESTO,CORAZA_TRAMPA,CORTAVIENTO,CORTE_VACIO,CRIOALIENTO_DESPIADADO,DANZA_DESPERTAR,DANZA_LLAMA,
    DANZA_PETALO,DEFLAGRACION_LUNAR,DESEO_OCULTO,DILUVIO_CORROSIVO,DISPARO_CERTERO,DISPARO_ESPEJO,DISPARO_LODO,
    DISRUPTOR_PSIQUICO,DISTORSION,DOBLE_RAYO,DRACOALIENTO_DEVASTADOR,DRACOENERGIA,DRAGOALIENTO,ECO_VOZ,ELECTORMENTA,
    ELECTROCAÑON,ELECTROJAULA,ELECTROTELA,ENERGIBOLA,ENVIDIA_ARDIENTE,ERUCTO,ESCALDAR,ESCUPIR,ESFERA_AURAL,
    ESPEAURA,ESTALLIDO,ESTOICISMO,ESTRUENDO,ESTRUENDO_IMPLACABLE,ESTRUJON,FIN_OSCURO,FOCO_RESPLANDOR,FOGONAZO,
    FOTODESTRUCCION_APOCALIPTICA,FRAGOR_ESCAMAS,FRIO_POLAR,FUEGO_OSCURO,FUERZA_LUNAR,FURIA_CANDENTE,FURIA_DRAGON,
    FURIA_NATURAL,GEISER_FOTONICO,GIRO_FUEGO,GLACEOPRISMA,GUADAÑA_SEDOSA,HECATOMBE_PIRICA,HELICE_TREPANADORA,
    HIDROBOMBA,HIDROCAÑON,HIDROPULSO,HIDROVORTICE_ABISAL,HIELO_OSCURO,HIERBA_LAZO,HIPERRAYO,HOJA_MAGICA,HUMAREDA,
    IMPACTRUENO,INFIERNO,INFORTUNIO,JOLTIOPARALISIS,JOYA_DE_LUZ,LANZALLAMAS,LASER_PRISMA,LIOFILIZACION,LLAMA_AZUL,
    LLAMA_EMBRUJADA,LLAMA_FINAL,LLAMA_FUSION,LLAMA_GELIDA,LLAMARADA,LLUEVEHOJAS,LLUVIA_IGNEA,LUZ_ANIQUILADORA,
    MANTO_ESPEJO,MARCHA_ESPECTRAL,MEGAAGOTAR,MEGATON_FLORAL,METALASER,METEOROBOLA,MIRADA_HELADORA,MOLUSCAÑON,
    MUNDO_GELIDO,A_DEFENDER,ABATIDORAS,ABSORBEFUERZA,ACUA_ARO,ACUPRESION,ADAPTACION,AFILAGARRAS,AFILAR,AGILIDAD
    ,AGUANTE,AGUZAR,ALIGERAR,ALIVIO,ALQUITRANAZO,AMNESIA,AMORTIGUADOR,ANEGAR,ANTICIPO,ANTICURA,ANULACION
    ,ARMADURA_ACIDA,AROMATERAPIA,ARRAIGO,ATAQUE_ARENA,ATIBORRAMIENTO,ATRACCION,AULLIDO,AURA_MAGNETICA,AUXILIO
    ,AVIVAR,AYUDA,BALSAMO_OSADO,BARRERA,BARRERA_ESPINOSA,BASTION_FINAL,BATIDO,BESO_AMOROSO,BESO_DULCE,BILIS,BLOQUEO,BOSTEZO,BRECHA_NEGRA
    ,BRUMA_OSCURA,BUNKER,CAMARADERIA,CAMBIA_ALMAS,CAMBIADEFENSA,CAMBIAFUERZA,CAMBIAPODER,CAMBIAVELOCIDAD,CAMBIO_DE_BANDA
    ,CAMBIO_DE_CANCHA,CAMBIO_DE_MARCHA,CAMELO,CAMPANA_CURA,CAMPO_DE_HIERBA,CAMPO_DE_NIEBLA,CAMPO_ELECTRICO
    ,CAMPO_PSIQUICO,CAMUFLAJE,CANTO,CANTO_MORTAL,CAPA_MAGICA,CARA_SUSTO,CARGA,CEDE_PASO,CELEBRACION,CERROJO_FEERICO,CHAPOTEO_LODO
    ,CHIRRIDO,CIELO_OSCURO,CLONATIPO,CONDENA_SILVANA,CONFIDENCIA,CONJURO,CONTONEO,CONVERSION,CONVERSION2,COPION,CORPULENCIA,CORTINA_PLASMA
    ,COSQUILLAS,CURA_FLORAL,CURA_SELVATICA,DANZA_ALETEO,DANZA_AMIGA,DANZA_CAOS,DANZA_DRAGON,DANZA_ESPADA,DANZA_LLUVIA
    ,DANZA_LUNAR,DANZA_PLUMA,DANZA_TRIUNFAL,DECORACION,DEFENSA_FERREA,DEFENSA_FLORAL,DESARROLLO,DESCANSO,DESEO,DESEO_CURA,DESLUMBRAR
    ,DESPEJAR,DESTELLO,DETECCION,DIA_SOLEADO,DISPARO_DEMORA,DIVIDE_DOLOR,DOBLE_EQUIPO,DRENADORAS,DULCE_AROMA,ECO_METALICO
    ,ELECTRIFICACION,EMBARGO,ENCANTO,ENROSQUE,ESCUDO_REAL,ESCUDO_TATAMI,ESPACIO_RARO,ESPEJO,ESPORA,ESPORAGODON,ESQUEMA
    ,ESTRUENDO_ESCAMA,FERTILIZANTE,FIJAR_BLANCO,FOCO,FOCO_ENERGIA,FORTALEZA,FUEGO_FATUO,GAS_CORROSIVO,GAS_VENENOSO,GEOCONTROL
    ,GOTA_VITAL,GRAN_OJO,GRANIZO,GRAVEDAD,GRUÑIDO,HALLOWEEN,HIDROCHORRO,HILO_VENENOSO,HIPNOSIS,HORA_DEL_TE,IMITACION
    ,INTERCAMBIO,ISOFUERZA,ISOGUARDIA,KINETICO,LATIGO,LEGADO,LEVITON,LLANTO_FALSO,LUZ_LUNAR,MAL_DE_OJO,MALDICION
    ,MALICIOSO,MANDATO,MANOS_JUNTAS,MAQUINACION,MAS_PSIQUE,MASA_COSMICA,MAXIBARRERA,MEDITACION,METRONOMO,MIEDO_OSCURO
    ,MIMETICO,MISMO_DESTINO,MITAD_OSCURA,MOFA,MOTIVACION,MUDA_OSCURA,NEBLINA,NIEBLA,NIEBLA_AROMATICA,NOVENA_POTENCIA,OBSTRUCCION, OCASO_OSCURO, OCTOPRESA, OFRENDA, OJITOS_TIERNOS, OJOS_LLOROSOS, ONDA_ANOMALA, ONDA_SIMPLE, ONDA_TRUENO, OTRA_VEZ, PAGA_EXTRA, PANTALLA_DE_HUMO, PANTALLA_DE_LUZ, PARALIZADOR, PAZ_MENTAL, PESADILLA, PIÑON_AUXILIAR, PLEGARIA_LUNAR, POLVO_EXPLOSIVO, POLVO_IRA, POLVO_MAGICO, POLVO_VENENO, PROFECIA, PROTECCION, PSICOCAMBIO, PUAS, A_BOCAJARRO, ACROBATA, ACUA_COLA, ACUA_JET, AGARRE, AGARRON, AGUIJON_LETAL, AGUJERO_NEGROANIQUILADOR, AL_ATAQUE, ALA_BIS, ALA_DE_ACERO, ALLANADOR_FERREO, ALUD, ALUVION_DE_FLECHAS_SOMBRIAS, AMAGO, ANCLAJE, ANTIAEREO, ANTOJO, ARAÑAZO, ARIETE, ARREMETIDA, ARROJO_INTEMPESTIVO, ARRUMACO, ARRUMAC_SIDERAL, ASALTO_BARRERA, ASALTO_ESTELAR, ASCENSO_DRACO, ASTA_DRENAJE, ATADURA, ATAQUE_AEREO, ATAQUE_ALA, ATAQUE_FULGOR, ATAQUE_FURIA, ATAQUE_OSEO, ATAQUE_RAPIDO, ATIZAR, AUTODESTRUCCION, AVALANCHA, AZOTE, AZOTE_TORRENCIAL, BALON_IGNEO, BARRENA_TELURIC, BATERIA_ASALTO, BOLA_HIELO
    ,BOMBA_GERMEN,BOMBA_HUEVO,BOMBA_IMAN,BOMBARDEO,BOTE,BRANQUIBOCADO,BRAZO_PINCHO,BRIO_OSCURO,BUCEO,BUCLE_ARENA,BUENA_BAZA
    ,CABEZA_DE_HIERRO,CABEZAZO,CABEZAZO_ZEN,CAIDA_LIBRE,CANTO_HELADO,CARAMBANO,CARANTOÑA,CARGA_DRAGON,CARGA_OSCURA
    ,CASCADA,CASTIGO,CEPO,CERCO_DIMENSION,CHISPA,CHOQUE_ANIMICO,CHULERIA,CHUPAVIDAS,CHUZOS,CLAVO_CAÑON,CLEMENCIA,
    COLA_DRAGON,COLA_FERREA,COLA_VENENO,COLMILLO_HIELO,COLMILLO_IGNEO,COLMILLO_RAYO,COLMILLO_VENENO,CONCHA_FILO
    ,CONSTELACION_ROBAALMAS,CONSTRICCION,CONTRAATAQUE,CORNADA,CORTE,CORTE_FURIA,CRIOALIENTO_DESPIADAD,CUCHILLA_SOLAR
    ,CUCHILLADA,CUERNO_CERTERO,CUERPO_PESADO,DAÑO_SECRETO,DEMOLICION
    ,DERRIBO,DESAHOGO,DESARME,DESQUITE,DESTRUCTOR,DIA_DE_PAGO,DILUVIO_CORROSIV,DISRUPTOR_PSIQUIC,DOBLE_ATAQUE,DOBLE_BOFETON
    ,DOBLE_FILO,DOBLE_GOLPE,DOBLE_PATADA,DON_NATURAL,DRACOALIENTO_DEVASTADO,DRACOFLECHAS,EEVIMPACTO,ELECTROPICO
    ,ELECTROPUNZADA,EMBATE_SUPREMO,EMBESTIDA_SOLAR,EMPUJON,ENFADO,ENVITE_ACUATICO,ENVITE_IGNEO,ERUPCION_DE_IRA,ESCARAMUZA
    ,ESFUERZO,ESPABILA,ESPADA_SANTA,ESTIMULO,EXCAVAR,EXPLOSION,FALSO_TORTAZO,FERROPUÑO_DOBLE,FILO_DEL_ABISMO,FINTA
    ,FISURA,FITOIMPULSO,FLAREMBESTIDA,FOLLAJE,FORCEJEO,FRUSTRACION,FUEGO_SAGRADO,FUERZA,FUERZA_BRUTA,FUERZA_EQUINA
    ,FUERZA_G,FUERZA_TELURICA,FURIA,GANCHO_ALTO,GARRA_BRUTAL,GARRA_DRAGON,GARRA_METAL,GARRA_NOCIVA,GARRA_UMBRIA
    ,GIRO_BOLA,GIRO_RAPIDO,GIRO_VIL,GOLPE,GOLPE_AEREO,GOLPE_BAJO,GOLPE_BIS,GOLPE_CABEZA,GOLPE_CALOR,GOLPE_CUERPO,GOLPE_FANTASMA;


    AllMoves() {
    }

    @Override
    public String toString() {
        return "allMoves{}";
    }
}
