public enum Objeto {

    AMBAR_VIEJO,AMULETO,ANTIDERRETIR,ARENA_FINA,BANDA_ATADURA,BANDA_FOCUS,BANDA_RECIA,BLANCO,BOLA_DE_NIEVE,
    BOLA_FERREA,BOLA_HUMO,BOLALUMINOSA,BOTON_ESCAPE,BRAZAL_FIRME,BRAZAL_RECIO,CAMPANA_ALIVIO,CAMPANA_CONCHA,
    CARBON,CASCO_DENTADO,CHALECO_ASALTO,CINTA_ELEGIDA,CINTA_EXPERTO,CINTA_FOCUS,CINTA_FUERTE,CINTO_RECIO,
    CINTURON_NEGRO,COLA_PLUMBEA,COLMILLO_DRAGON,CRIOROM,CUCHARA_TORCIDA,CUERDA_HUIDA,DIAMANSFERA,FLECHA_VENENOSA,
    FOSIL_ALETA,FOSIL_CORAZA,FOSIL_CRANEO,FOSIL_DOMO,FOSIL_GARRA,FOSIL_HELIX,FOSIL_MANDIBULA,FOSIL_PLUMA,FOSIL_RAIZ,
    FOSIL_TAPA,FRANJA_RECIA,FULGOROM,GAFA_PROTECTORA,GAFAS_DE_SOL,GAFAS_ELEGIDAS,GAFAS_ESPECIALES,GARRA_GARFIO,
    GARRA_RAPIDA,GEMA_ACERO,GEMA_AGUA,GEMA_BICHO,GEMA_DRAGON,GEMA_ELECTRICA,GEMA_FANTASMA,GEMA_FUEGO,GEMA_HADA,
    GEMA_HIELO,GEMA_NORMAL,GEMA_PLANTA,GEMA_PSIQUICA,GEMA_ROCA,GEMA_SINIESTRA,GEMA_TIERRA,GEMA_VENENO,GEMA_VOLADORA,
    GLOBO_HELIO,GRISEOSFERA,HECHIZO,HIDROROM,HIERBA_BLANCA,HIERBA_UNICA,HUESO_GRUESO,HUEVO_SUERTE,IMAN,LAZO_DESTINO,
    LENTE_RECIA,LLAMASFERA,LODO_NEGRO,LUPA,LUSTRESFERA,METRONOMO,MINERAL_EVOLUTIVO,MONEDA_AMULETO,MUDA_CONCHA,
    MUSGO_BRILLANTE,PALO,PANUELO_ELEGIDO,PANUELO_SEDA,PERISCOPIO,PESA_RECIA,PICO_AFILADO,PIEDRA_DURA,PIEDRA_ESPIRITU,
    PIEDRA_ETERNA,PIEDRA_POMEZ,PILA,PIROROM,POLVO_BRILLO,POLVO_METALICO,POLVO_PLATA,POLVO_VELOZ,PUNO_SUERTE,
    RAIZ_GRANDE,RESTOS,ROCA_CALOR,ROCA_HELADA,ROCA_LLUVIA,ROCA_SUAVE,ROCIO_BONDAD,SEGURO_DEBILIDAD,SEMILLA_MILAGRO,
    TARJETA_ROJA,TELESCOPIO,TOXIESTRELLA,TOXISFERA,TUBERCULO,VIDASFERA;

    Objeto() {
    }

    @Override
    public String toString() {
        return "Objeto{}";
    }
}



